spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thptnvn
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
